"""
A Snakefile is just a python file! You can do things like:
* import functions,
* create variables,
* perform calculations,
* write comments.

URL: https://raw.githubusercontent.com/samgdotson/2021-dotson-ms/refs/heads/master/data/uiuc_demand_data.csv
"""
configfile: "config.yml"

data_path = "data"
figure_path = "figures"

rule targets:
    input:
        plot = f"{figure_path}/dg_blog_plot.png",
        dag = "dag.png"

rule retrieve_data:
    output:
        dg_raw = f"{data_path}/dg_raw.csv", 
        nm_raw = f"{data_path}/nm_raw.csv", 
        nnm_raw = f"{data_path}/nnm_raw.csv", 
        central_raw = f"{data_path}/central_raw.csv", 
    script: "scripts/retrieve_data.py"

rule process_data:
    input: 
        dg_raw = f"{data_path}/dg_raw.csv", 
        nm_raw = f"{data_path}/nm_raw.csv", 
        nnm_raw = f"{data_path}/nnm_raw.csv", 
        central_raw = f"{data_path}/central_raw.csv", 
    output: 
        processed_data = f"{data_path}/processed_data.csv"
    script: "scripts/process_data.py" 

rule plot_data:
    input:
        processed_data = f"{data_path}/processed_data.csv"
    output: 
        plot = f"{figure_path}/dg_blog_plot.png"
    script: "scripts/plot_data.py"

rule build_dag:
    input: "Snakefile"
    output:
        "dag.png"
    shell:
        "snakemake --dag | dot -Tpng > {output}"